### ISSUE TITLE
Parsing does not warn about excess fields

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/omi#28] opened 2019-12-11 08:51 UTC
This might be an issue, because people may try to parse metadata with typos.

Will this be solved by #20?

**Comment by christian-rli** [comment] 2021-10-05 09:49
This is a duplicate of #36 . I know this one came first, but the other one has more comments, so I'm keeping the later one :)

**Closed by christian-rli** 2021-10-05 09:49 UTC
